// injectConfig.js (Updated to read individual parameters from Remote Config)

import fs from 'fs';
import path, { dirname } from 'path';
import { fileURLToPath } from 'url';
import admin from 'firebase-admin';

// Get __dirname equivalent in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

async function generateConfig() {
    try {
        // Initialize the Admin SDK
        // (Assumes service account credentials are set in your CI/CD environment)
        admin.initializeApp();

        // Fetch the entire Remote Config template
        const template = await admin.remoteConfig().getTemplate();
        const parameters = template.parameters;
        
        // Helper function to safely read a parameter value
        const getParamValue = (key) => {
            const param = parameters[key];
            if (!param || !param.defaultValue || !param.defaultValue.value) {
                // If the parameter is missing, this will throw an error to halt the build
                throw new Error(`Missing required Remote Config parameter: ${key}`);
            }
            return param.defaultValue.value;
        };

        // --- Retrieve each individual parameter ---
        // Use preview API key if provided (for PR preview environments), otherwise use Remote Config
        const apiKey = process.env.PREVIEW_API_KEY || getParamValue('API_KEY');
        const appId = getParamValue('APP_ID');
        const authDomain = getParamValue('AUTH_DOMAIN');
        const projectId = getParamValue('PROJECT_ID');
        const storageBucket = getParamValue('STORAGE_BUCKET');
        
        if (process.env.PREVIEW_API_KEY) {
            console.log('✅ Using preview API key for Firebase configuration');
        }


        // --- Format the config object for the frontend ---
        const fileContent = `
            // This file is auto-generated by injectConfig.js during build
            export const firebaseConfig = {
                apiKey: "${apiKey}",
                authDomain: "${authDomain}",
                projectId: "${projectId}",
                storageBucket: "${storageBucket}",
                appId: "${appId}",
            };
        `;
        
        const outputPath = path.join(__dirname, 'src', 'firebaseConfig.js');
        fs.writeFileSync(outputPath, fileContent);
        
        console.log(`✅ Generated Firebase config file at ${outputPath}`);

    } catch (error) {
        console.error("❌ Failed to generate config file from Remote Config. Ensure all ABC_ keys are set.");
        console.error(error);
        process.exit(1);
    }
}

generateConfig();
