export const WALKIN_CUSTOMER_STATUS = {
  INSIDE: 'INSIDE',
  OUTSIDE: 'OUTSIDE',
  CANCELLED: 'CANCELLED',
};

export const WALKIN_CUSTOMER_STATUS_LABELS = {
  [WALKIN_CUSTOMER_STATUS.INSIDE]: 'Inside',
  [WALKIN_CUSTOMER_STATUS.OUTSIDE]: 'Checked Out',
  [WALKIN_CUSTOMER_STATUS.CANCELLED]: 'Cancelled',
};
